# Generated by Django 2.2.2 on 2019-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190703_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=25)),
                ('phone', models.IntegerField(default=0, max_length=12)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
